# Generated by Django 6.0.2 on 2026-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
