# Generated by Django 6.0.2 on 2026-02-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0003_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
